### ISSUE TITLE
Since i cant open one on Mercury-Client

### ISSUE THREAD

**Issue by dashnullify** [Crystallinqq/mercurycapes#1]
Where is da credit on legit using Ingros base and some one Ingros Modules?? 
https://github.com/Crystallinqq/Mercury-Client

**Comment by Crystallinqq** [comment]
doesnt use ingros code. auto may have added mercury code into ingros as he is a dev for both but there is no code written for ingros in mercury.

**Comment by dashnullify** [comment]
That is legit a lie LOL its legit INGROS BASE nor was he a dev of INGROS i am legit one of the LEADERS of ingros this is legit ingros base with ingros modules. Give Credit where CREDIT is due.

**Comment by Crystallinqq** [comment]
proof?

**Comment by dashnullify** [comment]
https://hasteb.in/jimoyome.java https://github.com/Crystallinqq/Mercury-Client/blob/master/src/main/java/fail/mercury/client/api/loader/MercuryLoader.java

**Comment by dashnullify** [comment]
ALSO ohareware hud editor lmao

**Comment by Crystallinqq** [comment]
auto added both hud editor and the mixin loader

**Comment by dashnullify** [comment]
https://hasteb.in/obusuhas.java https://github.com/Crystallinqq/Mercury-Client/blob/master/src/main/java/fail/mercury/client/client/gui/hudeditor/GuiHud.java

**Comment by dashnullify** [comment]
yes so give credit HE WAS NOT A DEV OF INGROS

**Comment by Crystallinqq** [comment]
he is?

**Comment by Crystallinqq** [comment]
r u retarded?

**Comment by dashnullify** [comment]
NO HE ISNT LOL IM LEGIT THE LEADER OF INGROS LOL

**Comment by dashnullify** [comment]
weird he isnt on the repos for them??? if he is a dev why isnt he on the repos?

**Comment by Crystallinqq** [comment]
how would he paste if he didnt have it

**Comment by Crystallinqq** [comment]
or was a dev for it

**Comment by dashnullify** [comment]
LOL he had INGROS ??? ingros was never obfed

**Comment by Crystallinqq** [comment]
he had dev role in ingros discord b4 i was banned? ask ohare urself

**Comment by dashnullify** [comment]
IM LEGIT TALKING TO OHARE RN LOL he was NEVER a DEV of INGROS ??? if he was he WOULD BE IN THE REPOS???

**Comment by Crystallinqq** [comment]
r u xen?

**Comment by dashnullify** [comment]
even pasted our saving bruh just give credit where it is due

**Comment by Crystallinqq** [comment]
u didnt answer the question

**Comment by dashnullify** [comment]
does it matter? im just fighting for JUSTICE #JUSTICEFORINGROS

**Comment by Cuhnt** [comment]
4/10 troll please do better next time

**Comment by Crystallinqq** [comment]
yes it matters

**Comment by dashnullify** [comment]
wat?

**Comment by dashnullify** [comment]
u guys just hate gay people i guess omgosh

**Comment by Crystallinqq** [comment]
cuz if u r xen then u quit and have no business complaining about block game cheat

**Comment by dashnullify** [comment]
im reporting u to antifa

**Comment by Crystallinqq** [comment]
big man

**Comment by dashnullify** [comment]
im reporting u to antifa

**Comment by Crystallinqq** [comment]
i am going to laugh

**Comment by Crystallinqq** [comment]
1 sec have a chuckle coming up

**Comment by dashnullify** [comment]
it does matter im legit da project leader and leader of ingros and u guys are just pasters

**Comment by Crystallinqq** [comment]
u werent even in ingros discord

**Comment by dashnullify** [comment]
yes i was lol

**Comment by Crystallinqq** [comment]
when i was in ingros

**Comment by Crystallinqq** [comment]
no u werent

**Comment by dashnullify** [comment]
yes i was

**Comment by Crystallinqq** [comment]
the only people with dev role were zim, ohare and auto

**Comment by Crystallinqq** [comment]
no one named xen was in it monkey

**Comment by dashnullify** [comment]
hmm weird X3 didnt have a role????

**Comment by Crystallinqq** [comment]
what

**Comment by dashnullify** [comment]
yes me, chris and ohare all had dev role looool

**Comment by Crystallinqq** [comment]
doubt

**Comment by dashnullify** [comment]
ask ohare if im a leader and dev of ingros

**Comment by Crystallinqq** [comment]
i dont have his discord on my new account

**Comment by dashnullify** [comment]
u act like u know ingros but dont even know x3 loooool

**Comment by Crystallinqq** [comment]
i leaked it so im p sure ik

**Comment by dashnullify** [comment]
no u dont u legit dont even know who x3 is looool legit paster

**Comment by dashnullify** [comment]
ask auto if i was a dev of ingros

**Comment by Crystallinqq** [comment]
i have auto blocked lol

**Comment by Crystallinqq** [comment]
im not friends with him anymore

**Comment by dashnullify** [comment]
looooool u blocked ur boyfriend?

**Comment by Crystallinqq** [comment]
i dont have relationships with black people sorry

**Comment by Crystallinqq** [comment]
:^(

**Comment by Crystallinqq** [comment]
dont have time for shit bait

**Comment by dashnullify** [comment]
true auto is legit black
